# Generated by Django 3.1.6 on 2021-02-14 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudonym', models.CharField(max_length=15)),
                ('predictResult', models.PositiveSmallIntegerField(choices=[(1, 'No Use'), (2, 'Long Term'), (3, 'Short Term')])),
                ('predictDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_age', models.PositiveSmallIntegerField()),
                ('user_education', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')])),
                ('husband_education', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')])),
                ('number_children_ever_born', models.PositiveSmallIntegerField()),
                ('user_religion', models.PositiveSmallIntegerField(choices=[(0, 'Noneislam'), (1, 'Islam')])),
                ('user_working', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('husband_occupation', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very High')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictMethods.user')),
            ],
        ),
    ]
