# Generated by Django 3.1.6 on 2021-02-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictMethods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='predictDate',
            new_name='predict_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='predictResult',
            new_name='predict_result',
        ),
        migrations.AlterField(
            model_name='user',
            name='pseudonym',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_religion',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None Islam'), (1, 'Islam')]),
        ),
    ]
