# Generated by Django 3.1.6 on 2021-02-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictMethods', '0002_auto_20210216_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='predict_proba',
            field=models.FloatField(default=0),
        ),
    ]
